import type { TileDef } from "./types";
import { CRORE, LAKH } from "./constants";

// ==================== MUMBAI — 43 TILES ====================
// Serpentine board: Borivali (0) → Cuffe Parade Penthouse (42) → loop back.
// Prices in LAKHS. ₹1Cr = 100L.

export const TILES: TileDef[] = [
  // ───────────────────────────────────── ROW 1: WESTERN SUBURBS NORTH (L→R)
  {
    id: 0,
    name: "Borivali",
    area: "Western Terminus",
    type: "start",
    station: true,
    description: "Start. Pass GO — collect ₹2Cr salary.",
  },
  {
    id: 1,
    name: "Borivali East",
    area: "IC Colony",
    builder: "Rustomjee Group",
    type: "property",
    zone: "WSN",
    price: 8 * CRORE,
    baseRent: 80 * LAKH,
    fsi: 2.0,
    bus: true,
    redev: true,
  },
  {
    id: 2,
    name: "Dahisar",
    area: "Check Naka",
    builder: "Vijay Group",
    type: "property",
    zone: "WSN",
    price: 7 * CRORE,
    baseRent: 70 * LAKH,
    fsi: 2.0,
    redev: true,
  },
  {
    id: 3,
    name: "Kandivali West",
    area: "Mahavir Nagar",
    builder: "Oberoi Realty",
    type: "property",
    zone: "WSN",
    price: 10 * CRORE,
    baseRent: 100 * LAKH,
    fsi: 2.5,
    redev: true,
  },
  {
    id: 4,
    name: "Sanjay Gandhi Park",
    type: "tax",
    taxAmount: 3 * CRORE,
    description: "Environmental Cess. Pay ₹3Cr.",
  },
  {
    id: 5,
    name: "Malad West",
    area: "Evershine Nagar",
    builder: "Sheth Creators",
    type: "property",
    zone: "WSN",
    price: 11 * CRORE,
    baseRent: 110 * LAKH,
    fsi: 2.5,
    bus: true,
    redev: true,
  },

  // ───────────────────────────────────── ROW CONTINUED: WESTERN MID (L→R)
  {
    id: 6,
    name: "Goregaon East",
    area: "Film City",
    builder: "Lodha Group",
    type: "property",
    zone: "WSM",
    price: 12 * CRORE,
    baseRent: 120 * LAKH,
    fsi: 3.0,
    redev: true,
  },
  {
    id: 7,
    name: "Metro Line",
    type: "chance",
    description: "Mumbai Metro arrives. Draw a Chance card.",
  },
  {
    id: 8,
    name: "Goregaon West",
    area: "Lokhandwala Ext.",
    builder: "Oberoi Realty",
    type: "property",
    zone: "WSM",
    price: 13 * CRORE,
    baseRent: 130 * LAKH,
    fsi: 3.0,
    redev: true,
  },
  {
    id: 9,
    name: "Jogeshwari",
    area: "Oshiwara",
    builder: "Kalpataru",
    type: "property",
    zone: "WSM",
    price: 11 * CRORE,
    baseRent: 110 * LAKH,
    fsi: 2.5,
    redev: true,
  },
  {
    id: 10,
    name: "BEST Depot",
    type: "utility",
    price: 6 * CRORE,
    baseRent: 0,
    description: "BEST Bus utility. Rent = 10× dice total. +₹10L bonus from every bus rider.",
  },
  {
    id: 11,
    name: "Andheri West",
    area: "Lokhandwala",
    builder: "Rustomjee",
    type: "property",
    zone: "WSM",
    price: 15 * CRORE,
    baseRent: 150 * LAKH,
    fsi: 3.0,
    metro: true,
    bus: true,
    redev: true,
  },
  {
    id: 12,
    name: "Andheri East",
    area: "SEEPZ",
    builder: "Wadhwa Group",
    type: "property",
    zone: "WSM",
    price: 14 * CRORE,
    baseRent: 140 * LAKH,
    fsi: 3.0,
    redev: true,
  },
  {
    id: 13,
    name: "Versova",
    area: "Seven Bungalows",
    builder: "K Raheja Corp",
    type: "property",
    zone: "WSM",
    price: 16 * CRORE,
    baseRent: 160 * LAKH,
    fsi: 2.5,
    bus: true,
    redev: true,
  },

  // ───────────────────────────────────── BANDRA BELT (L→R)
  {
    id: 14,
    name: "BMC Ward Office",
    type: "community",
    description: "Society event. Draw a Community Chest card.",
  },
  {
    id: 15,
    name: "Vile Parle West",
    area: "Irla",
    builder: "Shapoorji Pallonji",
    type: "property",
    zone: "BB",
    price: 17 * CRORE,
    baseRent: 170 * LAKH,
    fsi: 3.0,
    redev: true,
  },
  {
    id: 16,
    name: "Santacruz West",
    area: "Linking Road",
    builder: "Kanakia Spaces",
    type: "property",
    zone: "BB",
    price: 18 * CRORE,
    baseRent: 180 * LAKH,
    fsi: 3.0,
    redev: true,
  },
  {
    id: 17,
    name: "Khar West",
    area: "Khar Danda",
    builder: "Rustomjee",
    type: "property",
    zone: "BB",
    price: 20 * CRORE,
    baseRent: 200 * LAKH,
    fsi: 3.5,
    bus: true,
    redev: true,
  },
  {
    id: 18,
    name: "Bandra Terminus",
    type: "station",
    station: true,
    price: 8 * CRORE,
    baseRent: 100 * LAKH,
    description: "Railway station. ₹8Cr to buy. Teleport to any station.",
  },
  {
    id: 19,
    name: "Bandra West",
    area: "Pali Hill ⭐",
    builder: "Lodha",
    type: "property",
    zone: "BB",
    price: 28 * CRORE,
    baseRent: 280 * LAKH,
    fsi: 2.0,
    premium: true,
    redev: true,
  },
  {
    id: 20,
    name: "BKC",
    area: "Bandra Kurla Complex",
    builder: "Radius",
    type: "property",
    zone: "BB",
    price: 26 * CRORE,
    baseRent: 260 * LAKH,
    fsi: 4.0,
    metro: true,
    redev: true,
  },

  // ───────────────────────────────────── SEA LINK CORRIDOR (R→L)
  {
    id: 21,
    name: "Sea Link Toll",
    type: "tax",
    taxAmount: 2 * CRORE,
    description: "Bandra–Worli Sea Link Toll. Pay ₹2Cr.",
  },
  {
    id: 22,
    name: "Mahim",
    area: "Causeway",
    builder: "Kalpataru",
    type: "property",
    zone: "SLC",
    price: 14 * CRORE,
    baseRent: 140 * LAKH,
    fsi: 3.0,
    bus: true,
    redev: true,
  },
  {
    id: 23,
    name: "Dadar West",
    area: "Shivaji Park ⭐",
    builder: "Sheth",
    type: "property",
    zone: "SLC",
    price: 19 * CRORE,
    baseRent: 190 * LAKH,
    fsi: 3.0,
    metro: true,
    premium: true,
    redev: true,
  },
  {
    id: 24,
    name: "Siddhivinayak",
    type: "chance",
    description: "Blessings from Ganpati Bappa. Draw a Chance card.",
  },
  {
    id: 25,
    name: "Prabhadevi",
    area: "NM Joshi Marg",
    builder: "Lodha",
    type: "property",
    zone: "SLC",
    price: 22 * CRORE,
    baseRent: 220 * LAKH,
    fsi: 4.0,
    redev: true,
  },
  {
    id: 26,
    name: "Worli",
    area: "Sea Face ⭐",
    builder: "Oberoi",
    type: "property",
    zone: "SLC",
    price: 32 * CRORE,
    baseRent: 320 * LAKH,
    fsi: 3.5,
    coastal: true,
    premium: true,
    redev: true,
  },
  {
    id: 27,
    name: "Jio Tower",
    type: "utility",
    price: 6 * CRORE,
    baseRent: 0,
    description: "Telecom utility. Rent = 4× dice total if one utility owned, 10× if both.",
  },
  {
    id: 28,
    name: "Lower Parel",
    area: "Kamala Mills",
    builder: "Indiabulls",
    type: "property",
    zone: "LPB",
    price: 24 * CRORE,
    baseRent: 240 * LAKH,
    fsi: 4.0,
    bus: true,
    redev: true,
  },

  // ───────────────────────────────────── LOWER PAREL BELT
  {
    id: 29,
    name: "Elphinstone",
    area: "Parel Village",
    builder: "Marathon",
    type: "property",
    zone: "LPB",
    price: 20 * CRORE,
    baseRent: 200 * LAKH,
    fsi: 3.5,
    redev: true,
  },
  {
    id: 30,
    name: "MHADA Lottery",
    type: "community",
    description: "Affordable housing lottery. Draw a Community Chest card.",
  },
  {
    id: 31,
    name: "Mahalaxmi",
    area: "Race Course ⭐",
    builder: "Shapoorji",
    type: "property",
    zone: "LPB",
    price: 27 * CRORE,
    baseRent: 270 * LAKH,
    fsi: 3.0,
    premium: true,
    redev: true,
  },
  {
    id: 32,
    name: "Tardeo",
    area: "Haji Ali",
    builder: "K Raheja",
    type: "property",
    zone: "LPB",
    price: 22 * CRORE,
    baseRent: 220 * LAKH,
    fsi: 3.0,
    redev: true,
  },
  {
    id: 33,
    name: "Mumbai Central",
    type: "station",
    station: true,
    price: 8 * CRORE,
    baseRent: 100 * LAKH,
    description: "Railway station. ₹8Cr to buy. Teleport to any station.",
  },

  // ───────────────────────────────────── SOUTH MUMBAI
  {
    id: 34,
    name: "Breach Candy",
    area: "Bhulabhai Desai ⭐",
    builder: "Lodha",
    type: "property",
    zone: "SM",
    price: 36 * CRORE,
    baseRent: 360 * LAKH,
    fsi: 2.0,
    bus: true,
    premium: true,
    redev: true,
  },
  {
    id: 35,
    name: "Nepean Sea Road",
    area: "Malabar Hill ⭐",
    builder: "Shapoorji",
    type: "property",
    zone: "SM",
    price: 40 * CRORE,
    baseRent: 400 * LAKH,
    fsi: 1.5,
    premium: true,
    redev: false,
  },
  {
    id: 36,
    name: "Stamp Duty Office",
    type: "tax",
    taxAmount: 4 * CRORE,
    description: "Stamp Duty + Registration. Pay ₹4Cr.",
  },
  {
    id: 37,
    name: "Girgaon",
    area: "Charni Road",
    builder: "Hiranandani",
    type: "property",
    zone: "SM",
    price: 28 * CRORE,
    baseRent: 280 * LAKH,
    fsi: 3.0,
    redev: true,
  },

  // ───────────────────────────────────── SOUTH MUMBAI PRIME
  {
    id: 38,
    name: "Marine Drive",
    area: "Queen's Necklace ⭐",
    builder: "Godrej",
    type: "property",
    zone: "SMP",
    price: 44 * CRORE,
    baseRent: 440 * LAKH,
    fsi: 1.5,
    metro: true,
    coastal: true,
    bus: true,
    premium: true,
    redev: false,
  },
  {
    id: 39,
    name: "Gateway of India",
    type: "chance",
    description: "Mumbai's icon. Draw a Chance card.",
  },
  {
    id: 40,
    name: "Churchgate",
    area: "Nariman Point ⭐",
    builder: "Tata Housing",
    type: "station",
    zone: "SMP",
    station: true,
    bus: true,
    price: 50 * CRORE,
    baseRent: 500 * LAKH,
    fsi: 2.0,
    premium: true,
    redev: true,
    description: "Station + premium office zone. Double duty.",
  },
  {
    id: 41,
    name: "Colaba",
    area: "Cuffe Parade ⭐",
    builder: "Raheja Universal",
    type: "property",
    zone: "SMP",
    price: 60 * CRORE,
    baseRent: 600 * LAKH,
    fsi: 1.5,
    premium: true,
    redev: false,
  },
  {
    id: 42,
    name: "Cuffe Parade Penthouse",
    type: "finish",
    description: "The finish line. Bonus ₹10Cr! Then loop back to Borivali.",
  },
];

export const TILE_COUNT = TILES.length;

export function getTile(id: number): TileDef {
  const t = TILES[((id % TILE_COUNT) + TILE_COUNT) % TILE_COUNT];
  if (!t) throw new Error(`Invalid tile id ${id}`);
  return t;
}

export function tilesInZone(zoneId: string): TileDef[] {
  return TILES.filter((t) => t.zone === zoneId);
}

export function isNorthOfBandra(tileId: number): boolean {
  return tileId >= 0 && tileId <= 17;
}

export function stationTiles(): number[] {
  return TILES.filter((t) => t.station).map((t) => t.id);
}

export function metroTiles(): number[] {
  return TILES.filter((t) => t.metro).map((t) => t.id);
}

export function busTiles(): number[] {
  return TILES.filter((t) => t.bus).map((t) => t.id);
}

export function coastalTiles(): number[] {
  return TILES.filter((t) => t.coastal).map((t) => t.id);
}
